server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone:  http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: springhr
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mouerxiaodui?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  resources:
    static-locations: classpath:/static
